FROM arch
EXPOSE 8000
WORKDIR /usr/share/webapps/gitlab
RUN pacman --noconfirm -Syu gitlab \
    && pacman --noconfirm -Scc
ENTRYPOINT [ \
    "bundle", "exec", "puma", \
    "-C", "config/puma.rb", "-e", "production"]
RUN pacman --noconfirm -Syu ruby-pg yarn \
    && pacman --noconfirm -Scc
ENV RAILS_ENV=production EXECJS_RUNTIME=Disabled
RUN chmod o+rx /var/lib/gitlab \
    && rm -r \
        /run/gitlab \
        /usr/share/webapps/gitlab/public/uploads \
        /var/log/gitlab \
        /var/tmp \
    && sed -i \
        -e '/batched_background_migrations_worker/s/\* \*/* 0/' \
        -e '/batched_background_migration_worker_ci_database/s/\* \*/* 0/' \
        /usr/share/webapps/gitlab/config/initializers/1_settings.rb
