FROM arch
COPY PKGBUILD character_limit.patch /tmp/mastodon/
EXPOSE 8000
WORKDIR /var/lib/mastodon
ENV RAILS_ENV=production
RUN pacman --noconfirm -Syu \
        base-devel corepack ffmpeg git libidn libvips libpqxx libxslt libyaml \
        nodejs protobuf ruby-bundler valkey \
    && useradd aur --home-dir /tmp/aur --create-home \
    && mkdir /tmp/yarn-berry \
    && cd /tmp/yarn-berry \
    && chown -R aur: . \
    && curl \
        https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=yarn-berry \
        -o PKGBUILD \
    && runuser -u aur -- makepkg \
    && pacman --noconfirm -U yarn-berry-*.pkg.tar.zst \
    && cd /tmp/mastodon \
    && chown -R aur: . \
    && curl \
        https://aur.archlinux.org/cgit/aur.git/plain/devise_pam.patch?h=mastodon \
        -o devise_pam.patch \
    && runuser -u aur -- makepkg \
    && pacman --noconfirm -U mastodon-*.pkg.tar.zst \
    && cd - \
    && rm -rf \
        /tmp/aur/ /tmp/yarn-berry/ /tmp/mastodon/ /tmp/bundler-*/ \
        /tmp/core-js-banners /tmp/v8-compile-cache-*/ /tmp/yarn-*/ \
        /tmp/.yarn-cache-*/ \
    && userdel aur \
    && pacman --noconfirm -R --recursive base-devel \
    && pacman --noconfirm -Scc
